# Generated by Django 5.0.6 on 2024-08-03 21:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_order_cart_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='menuitem',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('item', 'user')},
        ),
    ]
