# Generated by Django 5.0.6 on 2024-08-03 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_rename_menuitem_cart_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
