# Generated by Django 5.0.6 on 2024-08-03 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0004_remove_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='menuitem',
            new_name='item',
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'item')},
        ),
    ]
